import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: 1,
    axis: "time",
    axisLabel: "Thời gian thật",
    question: "Mỗi tuần bạn có mấy giờ cho mục tiêu này?",
    helper: "Tính theo quỹ thời gian thực tế, trừ đi lịch làm việc và sinh hoạt.",
    options: [
      {
        value: "lt1",
        label: "Dưới 1 giờ",
        score: 1,
        diagnostic: "Kế hoạch phải rất nhẹ, chỉ nên giữ 1-2 việc chính.",
        impact: "Điểm khả thi cực thấp. Cần kế hoạch siêu nhẹ để không bỏ cuộc.",
        example: "Chỉ rảnh 15 phút trước khi đi ngủ mỗi tối để lướt từ vựng.",
      },
      {
        value: "1to3",
        label: "Từ 1-3 giờ",
        score: 2,
        diagnostic: "Kế hoạch nên gọn, ít việc nhưng lặp đều.",
        impact: "Mức tải thấp. Phù hợp với 1-2 hành động nhỏ lặp lại đều đặn.",
        example: "Dành 20 phút mỗi ngày hoặc học 1.5 tiếng vào ngày nghỉ cuối tuần.",
      },
      {
        value: "3to5",
        label: "Từ 3-5 giờ",
        score: 3,
        diagnostic: "Có đủ chỗ cho một nhịp cân bằng.",
        impact: "Mức tải cân bằng. Đủ không gian cho một nhịp kỷ luật bền bỉ.",
        example: "Dành khoảng 30-45 phút mỗi tối sau giờ làm để làm việc/tập luyện.",
      },
      {
        value: "gt5",
        label: "Trên 5 giờ",
        score: 4,
        diagnostic: "Có thể làm nhiều hơn một chút nếu các phần khác cũng ổn.",
        impact: "Quỹ thời gian lý tưởng. Sẵn sàng cho việc tăng tốc sâu hơn.",
        example: "Dành 1 tiếng rưỡi mỗi ngày hoặc học cả buổi sáng thứ Bảy/Chủ nhật.",
      },
    ],
  },
  {
    id: 2,
    axis: "energy",
    axisLabel: "Năng lượng hiện tại",
    question: "Năng lượng còn lại của bạn sau ngày làm việc?",
    helper: "Để thiết kế tuần đầu tiên phù hợp với sức bền thực tế của bạn.",
    options: [
      {
        value: "energy_drained",
        label: "Thường đã cạn sức",
        score: 1,
        diagnostic: "Cần giảm việc và chọn khoảng thời gian rất nhỏ.",
        impact: "Nguy cơ trì hoãn cao. Cần việc siêu nhỏ tốn rất ít sức lực.",
        example: "Đi làm về chỉ muốn nằm nghỉ ngơi, đầu óc căng thẳng không muốn nghĩ thêm.",
      },
      {
        value: "energy_low",
        label: "Còn ít (dễ bỏ lỡ)",
        score: 2,
        diagnostic: "Cần thắng nhỏ sớm để giữ nhịp.",
        impact: "Dễ nản lòng. Cần lên lịch cụ thể và chọn việc dễ hoàn thành sớm.",
        example: "Hơi mệt nhưng vẫn đủ sức lướt điện thoại, đọc tin tức hoặc xem phim giải trí.",
      },
      {
        value: "energy_stable",
        label: "Đủ dùng (nếu lên lịch trước)",
        score: 3,
        diagnostic: "Có thể đi cân bằng nếu lịch được khóa rõ.",
        impact: "Đủ năng lượng nếu có lịch hẹn cố định trước để tạo thói quen tự nhiên.",
        example: "Vẫn đủ tỉnh táo làm việc chuyên môn nhẹ nếu đã cam kết và ghi lịch.",
      },
      {
        value: "energy_high",
        label: "Dồi dào & chủ động",
        score: 4,
        diagnostic: "Có thể giữ nhịp đều và tăng lượng việc từ từ.",
        impact: "Lý tưởng để duy trì nhịp liên tục và chịu được áp lực hành động cao.",
        example: "Luôn sẵn sàng bắt tay vào làm việc ngay với sự hăng hái và tập trung.",
      },
    ],
  },
  {
    id: 3,
    axis: "resources",
    axisLabel: "Nguồn lực / kỹ năng",
    question: "Bạn đã có đủ kỹ năng và công cụ cần thiết chưa?",
    helper: "Nếu thiếu, kế hoạch tuần đầu sẽ ưu tiên việc học hỏi và chuẩn bị.",
    options: [
      {
        value: "resources_missing",
        label: "Thiếu nhiều (cần học từ đầu)",
        score: 1,
        diagnostic: "Cần bước đệm học/chuẩn bị trước khi tăng tốc.",
        impact: "Cần thời gian chuẩn bị. Tuần 1 nên ưu tiên học kiến thức nền tảng trước.",
        example: "Muốn viết web bán hàng nhưng chưa biết tí gì về lập trình HTML/JS.",
      },
      {
        value: "resources_basic",
        label: "Có cơ bản (còn nhiều lỗ hổng)",
        score: 2,
        diagnostic: "Kế hoạch nên chừa chỗ cho học và điều chỉnh.",
        impact: "Nên vừa học vừa làm. Kế hoạch cần thêm thời gian để tìm hiểu thêm.",
        example: "Đã biết sơ qua lý thuyết Marketing nhưng chưa từng tự chạy quảng cáo thật.",
      },
      {
        value: "resources_mostly_ready",
        label: "Sẵn sàng 80% (bổ sung dần)",
        score: 3,
        diagnostic: "Có thể bắt đầu hành động chính song song với bổ sung.",
        impact: "Có thể thực thi ngay. Chỉ cần bổ sung công cụ/tài liệu phụ trợ dần dần.",
        example: "Đã có đủ tài liệu học và phần mềm, chỉ thiếu một vài hướng dẫn nâng cao.",
      },
      {
        value: "resources_ready",
        label: "Hoàn toàn sẵn sàng",
        score: 4,
        diagnostic: "Kế hoạch có thể tập trung nhiều hơn vào làm thật.",
        impact: "Tập trung 100% vào hành động thật để ra kết quả nhanh chóng nhất.",
        example: "Đã trang bị đầy đủ tài liệu, công cụ bản quyền và có kinh nghiệm thực tế.",
      },
    ],
  },
  {
    id: 4,
    axis: "clarity",
    axisLabel: "Độ rõ mục tiêu",
    question: "Mục tiêu này có thực sự rõ ràng với bạn?",
    helper: "Mục tiêu càng cụ thể, việc chia nhỏ theo tuần càng dễ dàng.",
    options: [
      {
        value: "overwhelming",
        label: "Quá lớn & choáng ngợp",
        score: 1,
        diagnostic: "Nên thu nhỏ mục tiêu trước khi tạo kế hoạch.",
        impact: "Dễ bị lạc lối. Cần thu nhỏ mục tiêu 12 tuần xuống 3 lần để chắc thắng.",
        example: "Muốn học giao tiếp thành thạo một ngôn ngữ mới từ số 0 trong vòng 12 tuần.",
      },
      {
        value: "challenging",
        label: "Thách thức (nhưng có thể làm)",
        score: 2,
        diagnostic: "Cần chọn một kết quả 12 tuần hẹp hơn.",
        impact: "Mục tiêu rộng. Cần chọn một khía cạnh cụ thể nhất để hành động.",
        example: "Muốn đọc xong 12 cuốn sách dày và viết tóm tắt chi tiết cho từng cuốn.",
      },
      {
        value: "realistic",
        label: "Thực tế (nếu giữ kỷ luật)",
        score: 3,
        diagnostic: "Có thể đi tiếp với nhịp cân bằng.",
        impact: "Mục tiêu vừa sức. Chỉ cần giữ đúng nhịp độ lặp lại để cán đích.",
        example: "Mục tiêu là hoàn thành 1 khóa học chuyên môn và tự làm 1 dự án nhỏ.",
      },
      {
        value: "very_realistic",
        label: "Cực kỳ rõ ràng & tự tin",
        score: 4,
        diagnostic: "Đủ rõ để chuyển sang kế hoạch 12 tuần.",
        impact: "Đã định hình rõ từng bước đi cụ thể. Sẵn sàng tạo kế hoạch ngay lập tức.",
        example: "Mục tiêu chạy liên tục được 5km không nghỉ (đã đo đạc lộ trình mỗi tuần).",
      },
    ],
  },
  {
    id: 5,
    axis: "obstacle",
    axisLabel: "Trở ngại chính",
    question: "Trở ngại lớn nhất có thể cản bước bạn?",
    helper: "Hãy gọi tên trở ngại để chúng ta chủ động tìm giải pháp phòng ngừa.",
    options: [
      {
        value: "motivation",
        label: "Dễ mất đà & động lực",
        score: 2,
        diagnostic: "Cần thắng nhỏ sớm và một lần nhìn lại ngắn mỗi tuần.",
        impact: "Cần thắng nhỏ sớm và thiết lập ngày nhìn lại cố định để duy trì cảm hứng.",
        example: "Hăng hái tột độ trong tuần đầu nhưng sang tuần thứ hai bắt đầu chán và lười.",
      },
      {
        value: "time",
        label: "Khó quản lý thời gian",
        score: 2,
        diagnostic: "Cần giảm số việc và khóa lịch cố định.",
        impact: "Dễ bị việc phát sinh đè lên. Cần giảm số việc và khóa lịch cố định trước.",
        example: "Lịch trình đột xuất từ gia đình hoặc việc làm thêm thường xuyên phá vỡ kế hoạch.",
      },
      {
        value: "resources",
        label: "Thiếu kiến thức/nguồn lực",
        score: 2,
        diagnostic: "Cần thêm bước học/chuẩn bị vào tuần đầu.",
        impact: "Dễ nản vì gặp lỗi khó. Cần ưu tiên hỏi han người đi trước hoặc tìm trợ giúp.",
        example: "Không biết tìm tài liệu chuẩn ở đâu hoặc gặp lỗi kỹ thuật mà không biết hỏi ai.",
      },
      {
        value: "complexity",
        label: "Mục tiêu quá phức tạp",
        score: 2,
        diagnostic: "Cần tách rõ phần bắt buộc và phần mở rộng.",
        impact: "Dễ bị sa lầy chi tiết. Cần tách rõ phần tối thiểu bắt buộc và phần mở rộng.",
        example: "Mục tiêu đòi hỏi quá nhiều khâu trung gian phụ thuộc lẫn nhau phức tạp.",
      },
      {
        value: "none",
        label: "Chưa thấy trở ngại nào",
        score: 4,
        diagnostic: "Có thể tập trung vào nhịp làm đều.",
        impact: "Mọi thứ sẵn sàng. Có thể tập trung hoàn toàn vào việc thực thi đều đặn.",
        example: "Không gian làm việc yên tĩnh, lịch sinh hoạt ổn định, tinh thần thoải mái.",
      },
    ],
  },
  {
    id: 6,
    axis: "routine",
    axisLabel: "Lịch cố định",
    question: "Bạn đã xếp lịch cố định cho mục tiêu chưa?",
    helper: "Khung giờ cố định giúp bạn xây dựng thói quen bền vững nhất.",
    options: [
      {
        value: "rarely",
        label: "Chưa (làm khi nhớ ra)",
        score: 1,
        diagnostic: "Kế hoạch phải bắt đầu bằng việc khóa lịch.",
        impact: "Dễ bị trôi ngày. Kế hoạch phải bắt đầu bằng việc khóa lịch cố định ngay.",
        example: "Nhớ ra thì tập luyện hoặc học bài, bận hay mệt thì tặc lưỡi bỏ qua cả tuần.",
      },
      {
        value: "sometimes",
        label: "Có dự định (hay bị xen ngang)",
        score: 2,
        diagnostic: "Cần lịch nhẹ và một lần nhìn lại để kéo lại nhịp.",
        impact: "Dễ bị lịch khác đè lên. Cần bảo vệ 1 khung giờ nhỏ nhất và nhìn lại tuần.",
        example: "Dự định tối thứ 2/4/6 sẽ học bài, nhưng thỉnh thoảng có bạn rủ đi chơi lại nghỉ.",
      },
      {
        value: "mostly",
        label: "Có vài khung giờ khá ổn",
        score: 3,
        diagnostic: "Có thể giữ nhịp cân bằng nếu không thêm quá nhiều việc.",
        impact: "Cơ sở tốt để giữ nhịp. Chỉ cần cam kết lịch nhìn lại để kiểm soát độ đều.",
        example: "Thường tự học/tập luyện được vào 2-3 buổi tối cố định trong tuần.",
      },
      {
        value: "always",
        label: "Đã khóa lịch cố định",
        score: 4,
        diagnostic: "Nền lịch đủ tốt để triển khai đều hơn.",
        impact: "Nền tảng kỷ luật lý tưởng để duy trì liên tục và dễ dàng nâng dần độ khó.",
        example: "Khóa chặt lịch 5:30 - 6:00 sáng mỗi ngày để đọc sách và thiền (không đổi).",
      },
    ],
  },
  {
    id: 7,
    axis: "confidence",
    axisLabel: "Tự tin hoàn thành",
    question: "Độ tự tin hoàn thành tuần đầu tiên của bạn?",
    helper: "Hãy lắng nghe cảm giác thật để thiết kế một khởi đầu thắng lợi.",
    options: [
      {
        value: "exploring",
        label: "Còn khá do dự",
        score: 1,
        diagnostic: "Cần thu nhỏ để tạo niềm tin ban đầu.",
        impact: "Dễ nản khi gặp khó. Cần thu nhỏ việc tuần đầu xuống cực đại để lấy đà.",
        example: "Lo lắng không chắc mình có thể duy trì thói quen quá 2 tuần liên tiếp.",
      },
      {
        value: "interested",
        label: "Cần một kế hoạch thật rõ",
        score: 2,
        diagnostic: "Cần ít việc lặp lại và chỉ số đo đơn giản.",
        impact: "Cần bảng Check-in trực quan để bám sát và tích xanh mỗi ngày.",
        example: "Sợ quên việc nếu không có bảng danh sách theo dõi rõ ràng, chi tiết.",
      },
      {
        value: "ready",
        label: "Tự tin (nếu tuần đầu vừa sức)",
        score: 3,
        diagnostic: "Có thể đi cân bằng với tuần đầu nhẹ.",
        impact: "Tự tin vừa đủ. Cơ hội thắng cao nếu tuần đầu nhẹ nhàng để làm quen nhịp.",
        example: "Tin tưởng bản thân làm được nếu kế hoạch không quá dồn dập lúc bắt đầu.",
      },
      {
        value: "committed",
        label: "Sẵn sàng chiến đấu ngay",
        score: 4,
        diagnostic: "Có thể bắt đầu ngay, miễn là không làm kế hoạch phình quá rộng.",
        impact: "Quyết tâm cao độ. Hãy giữ nhịp đều đặn, tránh hưng phấn quá đà lúc đầu.",
        example: "Đã chuẩn bị sẵn tinh thần đối mặt trở ngại, háo hức muốn bắt tay vào làm ngay.",
      },
    ],
  },
];
