import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: 1,
    axis: "time",
    axisLabel: "Thời gian thật",
    question: "Mỗi tuần bạn có mấy giờ cho mục tiêu này?",
    helper: "Tính theo quỹ thời gian thực tế, trừ đi lịch làm việc và sinh hoạt.",
    options: [
      {
        value: "lt1",
        label: "Dưới 1 giờ",
        score: 1,
        diagnostic: "Kế hoạch phải rất nhẹ, chỉ nên giữ 1-2 việc chính.",
      },
      { value: "1to3", label: "Từ 1-3 giờ", score: 2, diagnostic: "Kế hoạch nên gọn, ít việc nhưng lặp đều." },
      { value: "3to5", label: "Từ 3-5 giờ", score: 3, diagnostic: "Có đủ chỗ cho một nhịp cân bằng." },
      {
        value: "gt5",
        label: "Trên 5 giờ",
        score: 4,
        diagnostic: "Có thể làm nhiều hơn một chút nếu các phần khác cũng ổn.",
      },
    ],
  },
  {
    id: 2,
    axis: "energy",
    axisLabel: "Năng lượng hiện tại",
    question: "Năng lượng còn lại của bạn sau ngày làm việc?",
    helper: "Để thiết kế tuần đầu tiên phù hợp với sức bền thực tế của bạn.",
    options: [
      {
        value: "energy_drained",
        label: "Thường đã cạn sức",
        score: 1,
        diagnostic: "Cần giảm việc và chọn khoảng thời gian rất nhỏ.",
      },
      {
        value: "energy_low",
        label: "Còn ít (dễ bỏ lỡ)",
        score: 2,
        diagnostic: "Cần thắng nhỏ sớm để giữ nhịp.",
      },
      {
        value: "energy_stable",
        label: "Đủ dùng (nếu lên lịch trước)",
        score: 3,
        diagnostic: "Có thể đi cân bằng nếu lịch được khóa rõ.",
      },
      {
        value: "energy_high",
        label: "Dồi dào & chủ động",
        score: 4,
        diagnostic: "Có thể giữ nhịp đều và tăng lượng việc từ từ.",
      },
    ],
  },
  {
    id: 3,
    axis: "resources",
    axisLabel: "Nguồn lực / kỹ năng",
    question: "Bạn đã có đủ kỹ năng và công cụ cần thiết chưa?",
    helper: "Nếu thiếu, kế hoạch tuần đầu sẽ ưu tiên việc học hỏi và chuẩn bị.",
    options: [
      {
        value: "resources_missing",
        label: "Thiếu nhiều (cần học từ đầu)",
        score: 1,
        diagnostic: "Cần bước đệm học/chuẩn bị trước khi tăng tốc.",
      },
      {
        value: "resources_basic",
        label: "Có cơ bản (còn nhiều lỗ hổng)",
        score: 2,
        diagnostic: "Kế hoạch nên chừa chỗ cho học và điều chỉnh.",
      },
      {
        value: "resources_mostly_ready",
        label: "Sẵn sàng 80% (bổ sung dần)",
        score: 3,
        diagnostic: "Có thể bắt đầu hành động chính song song với bổ sung.",
      },
      {
        value: "resources_ready",
        label: "Hoàn toàn sẵn sàng",
        score: 4,
        diagnostic: "Kế hoạch có thể tập trung nhiều hơn vào làm thật.",
      },
    ],
  },
  {
    id: 4,
    axis: "clarity",
    axisLabel: "Độ rõ mục tiêu",
    question: "Mục tiêu này có thực sự rõ ràng với bạn?",
    helper: "Mục tiêu càng cụ thể, việc chia nhỏ theo tuần càng dễ dàng.",
    options: [
      {
        value: "overwhelming",
        label: "Quá lớn & choáng ngợp",
        score: 1,
        diagnostic: "Nên thu nhỏ mục tiêu trước khi tạo kế hoạch.",
      },
      {
        value: "challenging",
        label: "Thách thức (nhưng có thể làm)",
        score: 2,
        diagnostic: "Cần chọn một kết quả 12 tuần hẹp hơn.",
      },
      {
        value: "realistic",
        label: "Thực tế (nếu giữ kỷ luật)",
        score: 3,
        diagnostic: "Có thể đi tiếp với nhịp cân bằng.",
      },
      {
        value: "very_realistic",
        label: "Cực kỳ rõ ràng & tự tin",
        score: 4,
        diagnostic: "Đủ rõ để chuyển sang kế hoạch 12 tuần.",
      },
    ],
  },
  {
    id: 5,
    axis: "obstacle",
    axisLabel: "Trở ngại chính",
    question: "Trở ngại lớn nhất có thể cản bước bạn?",
    helper: "Hãy gọi tên trở ngại để chúng ta chủ động tìm giải pháp phòng ngừa.",
    options: [
      {
        value: "motivation",
        label: "Dễ mất đà & động lực",
        score: 2,
        diagnostic: "Cần thắng nhỏ sớm và một lần nhìn lại ngắn mỗi tuần.",
      },
      { value: "time", label: "Khó quản lý thời gian", score: 2, diagnostic: "Cần giảm số việc và khóa lịch cố định." },
      {
        value: "resources",
        label: "Thiếu kiến thức/nguồn lực",
        score: 2,
        diagnostic: "Cần thêm bước học/chuẩn bị vào tuần đầu.",
      },
      {
        value: "complexity",
        label: "Mục tiêu quá phức tạp",
        score: 2,
        diagnostic: "Cần tách rõ phần bắt buộc và phần mở rộng.",
      },
      {
        value: "none",
        label: "Chưa thấy trở ngại nào",
        score: 4,
        diagnostic: "Có thể tập trung vào nhịp làm đều.",
      },
    ],
  },
  {
    id: 6,
    axis: "routine",
    axisLabel: "Lịch cố định",
    question: "Bạn đã xếp lịch cố định cho mục tiêu chưa?",
    helper: "Khung giờ cố định giúp bạn xây dựng thói quen bền vững nhất.",
    options: [
      {
        value: "rarely",
        label: "Chưa (làm khi nhớ ra)",
        score: 1,
        diagnostic: "Kế hoạch phải bắt đầu bằng việc khóa lịch.",
      },
      {
        value: "sometimes",
        label: "Có dự định (hay bị xen ngang)",
        score: 2,
        diagnostic: "Cần lịch nhẹ và một lần nhìn lại để kéo lại nhịp.",
      },
      {
        value: "mostly",
        label: "Có vài khung giờ khá ổn",
        score: 3,
        diagnostic: "Có thể giữ nhịp cân bằng nếu không thêm quá nhiều việc.",
      },
      {
        value: "always",
        label: "Đã khóa lịch cố định",
        score: 4,
        diagnostic: "Nền lịch đủ tốt để triển khai đều hơn.",
      },
    ],
  },
  {
    id: 7,
    axis: "confidence",
    axisLabel: "Tự tin hoàn thành",
    question: "Độ tự tin hoàn thành tuần đầu tiên của bạn?",
    helper: "Hãy lắng nghe cảm giác thật để thiết kế một khởi đầu thắng lợi.",
    options: [
      {
        value: "exploring",
        label: "Còn khá do dự",
        score: 1,
        diagnostic: "Cần thu nhỏ để tạo niềm tin ban đầu.",
      },
      {
        value: "interested",
        label: "Cần một kế hoạch thật rõ",
        score: 2,
        diagnostic: "Cần ít việc lặp lại và chỉ số đo đơn giản.",
      },
      {
        value: "ready",
        label: "Tự tin (nếu tuần đầu vừa sức)",
        score: 3,
        diagnostic: "Có thể đi cân bằng với tuần đầu nhẹ.",
      },
      {
        value: "committed",
        label: "Sẵn sàng chiến đấu ngay",
        score: 4,
        diagnostic: "Có thể bắt đầu ngay, miễn là không làm kế hoạch phình quá rộng.",
      },
    ],
  },
];
