import type { EntitlementKey, PricingPlanCode } from "../storage-types";
import type { PricingPlanDefinition, TwelveWeekTemplateDefinition } from "./types";

export const PLAN_DEFINITIONS: PricingPlanDefinition[] = [
  {
    code: "FREE",
    name: "Free",
    shortLabel: "Free",
    priceLabel: "0đ",
    description: "Đủ để bạn chạy một chu kỳ 12 tuần hoàn chỉnh và biết hôm nay cần làm gì.",
    highlights: ["1 chu kỳ 12 tuần", "Today queue + check-in", "Review tuần cơ bản"],
  },
  {
    code: "PLUS",
    name: "Plus",
    shortLabel: "Plus",
    priceLabel: "149.000đ / chu kỳ",
    description: "Lớp Plus cho người muốn setup nhanh, giữ nhịp đều và có gợi ý review tuần sau.",
    highlights: [
      "Khung gợi ý thích nghi theo kiểu mục tiêu",
      "Review premium với gợi ý tuần sau",
      "Nhắc việc ưu tiên + analytics nâng cao",
    ],
  },
];

export const PLAN_ENTITLEMENTS: Record<PricingPlanCode, EntitlementKey[]> = {
  FREE: [],
  PLUS: ["premium_templates", "premium_review_insights", "priority_reminders", "advanced_analytics"],
  PRO: ["premium_templates", "premium_review_insights", "priority_reminders", "advanced_analytics"],
};

export const TWELVE_WEEK_TEMPLATE_CATALOG: TwelveWeekTemplateDefinition[] = [
  {
    id: "steady-focus-reset",
    name: "Quay lại nhịp gọn",
    subtitle: "Khung gợi ý Free",
    description: "Dành cho lúc bạn cần cắt loãng, quay lại nhịp và làm ít nhưng chắc.",
    bestFor: "Lúc bạn vừa bị rơi nhịp, đang ôm quá tay, hoặc muốn một chu kỳ thật gọn để quay lại.",
    whyItWorks: "Khung này thắng bằng độ đều. Bạn chỉ giữ vài nhịp lặp đơn giản nên rất khó vỡ tuần đầu.",
    firstWeekWin: "Tuần đầu chỉ cần chốt 1 việc cốt lõi mỗi ngày và review ngắn cuối ngày để nhịp quay lại ngay.",
    idealFor: ["Rơi nhịp gần đây", "Quá tải", "Muốn làm ít mà đều"],
    goalType: "Personal Growth",
    reviewDay: "Sunday",
    requiredPlan: null,
    accent: "slate",
    vision12Week: "Trong 12 tuần tới, tôi muốn dựng lại một nhịp làm việc gọn, rõ và ít ma sát hơn mỗi ngày.",
    week12Outcome: "Giữ được nhịp làm việc ít nhất 5 ngày mỗi tuần mà không còn cảm giác ôm quá tay.",
    lagMetricName: "Số ngày giữ đúng nhịp mỗi tuần",
    lagMetricTarget: "5",
    lagMetricUnit: "ngày/tuần",
    week4Milestone: "Nhịp tuần không còn bị đứt quá 2 ngày liên tiếp.",
    week8Milestone: "Có một lịch làm việc đủ nhẹ để giữ đều ngay cả khi bận.",
    successEvidence: "Bạn nhìn vào tuần nào cũng biết việc ưu tiên số 1 là gì.",
    tactics: [
      { name: "Chốt 1 việc cốt lõi mỗi ngày", target: "5", unit: "lần/tuần", type: "core", cadence: "spread" },
      { name: "Review cuối ngày 3 phút", target: "5", unit: "lần/tuần", type: "core", cadence: "spread" },
    ],
  },
  {
    id: "study-sprint-basics",
    name: "Đều và bền",
    subtitle: "Khung gợi ý Free",
    description: "Khi mục tiêu cần tiến đều từng tuần, không cần nước rút mạnh nhưng phải tích lũy thật.",
    bestFor: "Khi bạn muốn giữ nhịp bền, không cần tăng tốc mạnh nhưng vẫn phải thấy tiến triển đều.",
    whyItWorks: "Khung này cân giữa tiến độ chính và một vòng rà lại nhẹ, nên tuần nào cũng có bước tiến thật.",
    firstWeekWin: "Tuần đầu đã có nhịp tiến độ chính, nhịp rà lại và một review tuần rất nhẹ để giữ đều.",
    idealFor: ["Xây thói quen", "Tích lũy từng tuần", "Muốn tiến đều"],
    goalType: "Xây thói quen",
    reviewDay: "Sunday",
    requiredPlan: null,
    accent: "sky",
    vision12Week:
      "Trong 12 tuần tới, tôi muốn giữ một nhịp tiến đều để mục tiêu đi lên mà không phải ép nước rút liên tục.",
    week12Outcome: "Tích lũy đủ 12 tuần tiến đều và không còn cảm giác tuần nào cũng phải bắt đầu lại từ đầu.",
    lagMetricName: "Số phiên tiến độ chính",
    lagMetricTarget: "4",
    lagMetricUnit: "phiên/tuần",
    week4Milestone: "Nhịp tuần đã ổn định và biết rõ việc chính tuần nào cũng phải chạm.",
    week8Milestone: "Tốc độ tiến lên đều hơn và review tuần không còn nặng đầu.",
    successEvidence: "Bạn nhìn vào tuần nào cũng thấy rõ một bước tiến thật, dù nhỏ.",
    tactics: [
      { name: "Slot tiến độ chính", target: "4", unit: "phiên/tuần", type: "core", cadence: "spread" },
      { name: "Rà lại và khóa việc kế tiếp", target: "2", unit: "lần/tuần", type: "core", cadence: "backload" },
      { name: "Bổ sung một bước nhỏ", target: "1", unit: "lần/tuần", type: "optional", cadence: "spread" },
    ],
  },
  {
    id: "job-search-pipeline",
    name: "Ít nhưng phải ra đầu ra",
    subtitle: "Khung gợi ý Plus",
    description: "Khung Plus cho mục tiêu cần tạo đầu ra rõ mỗi tuần, không chỉ bận mà không tiến.",
    bestFor: "Khi bạn cần mỗi tuần phải có thứ gì đó được hoàn tất, nộp, đăng, gửi hoặc hoàn thành.",
    whyItWorks: "Mọi tactic đều bị kéo về một đầu ra chính, nên tuần không bị nuốt bởi việc phụ.",
    firstWeekWin: "Tuần đầu đã có slot tạo đầu ra, slot hoàn thiện và một nhịp follow-up nhẹ để đóng vòng.",
    idealFor: ["Ra đầu ra", "Hoàn tất dự án", "Chốt phần việc"],
    goalType: "Project Completion",
    reviewDay: "Friday",
    requiredPlan: "PLUS",
    accent: "emerald",
    vision12Week: "Trong 12 tuần tới, tôi muốn mỗi tuần đều có một đầu ra thật thay vì chỉ bận mà không chạm đích.",
    week12Outcome: "Có một chuỗi 12 tuần mà hầu như tuần nào cũng ra được đầu ra rõ ràng và đo được.",
    lagMetricName: "Số đầu ra đã chốt",
    lagMetricTarget: "2",
    lagMetricUnit: "đầu ra/tuần",
    week4Milestone: "Đã giữ được nhịp ra đầu ra tối thiểu mỗi tuần.",
    week8Milestone: "Không còn tuần nào bị trôi qua mà không chốt được một thứ thật.",
    successEvidence: "Bạn luôn biết tuần này đầu ra cần chốt là gì và đang ở giai đoạn nào.",
    tactics: [
      { name: "Tạo bản nháp hoặc phiên bản đầu", target: "2", unit: "phiên/tuần", type: "core", cadence: "frontload" },
      { name: "Hoàn thiện để chốt đầu ra", target: "2", unit: "phiên/tuần", type: "core", cadence: "backload" },
      { name: "Follow-up hoặc công bố", target: "1", unit: "lần/tuần", type: "optional", cadence: "spread" },
    ],
  },
  {
    id: "creator-publishing-engine",
    name: "Tăng tốc có kiểm soát",
    subtitle: "Khung gợi ý Plus",
    description: "Khung Plus cho lúc mục tiêu đủ khả thi để tăng tải nhẹ nhưng không muốn tự làm rối mình.",
    bestFor: "Khi bạn đã có độ sẵn sàng khá tốt và muốn đẩy nhanh tiến độ mà vẫn kiểm soát được nhịp.",
    whyItWorks: "Nó giữ 2 trục cốt lõi và một lớp mở rộng, nên bạn tăng tốc mà vẫn còn khoảng thở để không vỡ tuần.",
    firstWeekWin: "Tuần đầu đã có nhịp tăng tốc rõ nhưng vẫn giữ được ngày review và khoảng thở cần thiết.",
    idealFor: ["Muốn tăng tốc", "Đã có nền tảng", "Cần nhịp nước rút vừa phải"],
    goalType: "Personal Growth",
    reviewDay: "Friday",
    requiredPlan: "PLUS",
    accent: "violet",
    vision12Week: "Trong 12 tuần tới, tôi muốn tăng tốc đúng lúc nhưng vẫn giữ cho hệ thực thi đủ gọn để bám lâu.",
    week12Outcome: "Đẩy tiến độ nhanh hơn rõ rệt mà không bị hụt hơi sau vài tuần đầu.",
    lagMetricName: "Số đầu ra cốt lõi đã chốt",
    lagMetricTarget: "2",
    lagMetricUnit: "đầu ra/tuần",
    week4Milestone: "Nhịp tăng tốc đã vào guồng nhưng chưa làm tuần bị loãng.",
    week8Milestone: "Giữ được tốc độ cao hơn mà review tuần vẫn còn rõ đầu óc.",
    successEvidence: "Bạn nhìn vào tuần là biết đâu là lớp cốt lõi, đâu là lớp tăng tốc thêm.",
    tactics: [
      { name: "Phiên sâu cho việc chính", target: "3", unit: "phiên/tuần", type: "core", cadence: "frontload" },
      { name: "Chốt đầu ra hoặc gửi đi", target: "2", unit: "lần/tuần", type: "core", cadence: "spread" },
      { name: "Đẩy thêm lớp mở rộng", target: "1", unit: "lần/tuần", type: "optional", cadence: "backload" },
    ],
  },
  {
    id: "strength-and-energy-system",
    name: "Nhiều lớp nhưng không vỡ nhịp",
    subtitle: "Khung gợi ý Plus",
    description:
      "Khung Plus cho mục tiêu nhiều lớp khi bạn vừa phải làm việc chính, vừa giữ nhịp nền mà vẫn muốn tuần đủ nhẹ.",
    bestFor:
      "Khi mục tiêu có nhiều lớp kéo cùng lúc nhưng bạn vẫn muốn hệ thống biết chỗ nào phải giữ, chỗ nào có thể buông.",
    whyItWorks: "Khung này tách rõ phần bắt buộc, phần giữ nền và phần tùy sức, nên mục tiêu phức tạp vẫn đi được.",
    firstWeekWin: "Tuần đầu đã có phân lớp cốt lõi, nhịp giữ nền và chỗ để buông bớt khi cần.",
    idealFor: ["Mục tiêu nhiều lớp", "Vừa việc chính vừa việc nền", "Muốn cứu nhịp sớm"],
    goalType: "Personal Growth",
    reviewDay: "Sunday",
    requiredPlan: "PLUS",
    accent: "amber",
    vision12Week:
      "Trong 12 tuần tới, tôi muốn theo đuổi một mục tiêu nhiều lớp mà không để tuần nào cũng bị nặng đầu hoặc vỡ nhịp.",
    week12Outcome: "Giữ được phần cốt lõi, phần nền và phần mở rộng đúng chỗ mà không còn cảm giác mọi thứ dồn cục.",
    lagMetricName: "Số lớp việc được giữ đúng nhịp",
    lagMetricTarget: "3",
    lagMetricUnit: "lớp/tuần",
    week4Milestone: "Biết rõ lớp nào là bắt buộc và lớp nào chỉ làm khi còn sức.",
    week8Milestone: "Tuần nhiều việc hơn nhưng vẫn không bị mất phương hướng.",
    successEvidence: "Bạn nhìn vào lịch là biết việc nào phải giữ, việc nào có thể lùi mà không thấy tội lỗi.",
    tactics: [
      { name: "Lớp việc chính", target: "3", unit: "lần/tuần", type: "core", cadence: "spread" },
      { name: "Lớp giữ nền", target: "2", unit: "lần/tuần", type: "core", cadence: "spread" },
      { name: "Lớp mở rộng khi còn sức", target: "2", unit: "lần/tuần", type: "optional", cadence: "backload" },
    ],
  },
  {
    id: "exam-deep-study",
    name: "Học sâu không dàn trải",
    subtitle: "Khung gợi ý Plus",
    description:
      "Khung Plus cho kỳ thi hoặc mục tiêu học có deadline rõ. Giữ tiến độ đều, kiểm tra mức nắm và về đích trước ngày thi.",
    bestFor:
      "Khi bạn có một kỳ thi, kỳ sát hạch hoặc deadline học rõ ràng và cần một nhịp học không bị gián đoạn trong 12 tuần.",
    whyItWorks:
      "Khung này tách riêng slot học chủ động, slot ôn và slot kiểm tra hiểu, nên bạn không chỉ đọc mà còn biết mình nắm đến đâu.",
    firstWeekWin: "Tuần đầu đã có nhịp học chủ động, ôn lại và một vòng kiểm tra mức hiểu để biết điểm hổng sớm.",
    idealFor: ["Thi cử", "Học có deadline", "Cần tiến đều từng tuần"],
    goalType: "Exam / Study",
    reviewDay: "Sunday",
    requiredPlan: "PLUS",
    accent: "sky",
    vision12Week: "Trong 12 tuần tới, tôi muốn học sâu, ôn đúng chỗ và vào ngày thi không còn cảm giác phải nhồi nhét.",
    week12Outcome: "Hoàn thành toàn bộ nội dung cần học, có ít nhất 2 lần ôn tổng hợp và cảm giác vào thi đã đủ chắc.",
    lagMetricName: "Số buổi học chủ động mỗi tuần",
    lagMetricTarget: "4",
    lagMetricUnit: "buổi/tuần",
    week4Milestone: "Xong phần nền và biết rõ chỗ nào cần ôn thêm.",
    week8Milestone: "Đã học qua toàn bộ nội dung, bắt đầu chu kỳ ôn chủ động.",
    successEvidence: "Bạn ngồi vào buổi học là biết ngay hôm nay sẽ nắm thêm phần nào và kiểm tra bằng cách nào.",
    tactics: [
      { name: "Buổi học chủ động mới", target: "3", unit: "buổi/tuần", type: "core", cadence: "spread" },
      { name: "Ôn và consolidate", target: "2", unit: "lần/tuần", type: "core", cadence: "backload" },
      {
        name: "Kiểm tra mức hiểu (quiz/flashcard)",
        target: "1",
        unit: "lần/tuần",
        type: "optional",
        cadence: "spread",
      },
    ],
  },
  {
    id: "fitness-consistency-engine",
    name: "Vào guồng sức khỏe bền",
    subtitle: "Khung gợi ý Plus",
    description:
      "Khung Plus cho mục tiêu sức khỏe cần nhịp đều hơn là nước rút. Giữ tập, theo dõi phục hồi và ghi lại tiến triển thật.",
    bestFor: "Khi bạn muốn tập luyện thành thói quen bền, không chỉ bứt phá được vài tuần rồi đứt quãng.",
    whyItWorks:
      "Nhịp tập cốt lõi được bảo vệ, phần phục hồi được đo và chỉ số chính là tiến bộ thật, không phải cảm giác.",
    firstWeekWin: "Tuần đầu đã có 3 buổi tập chất lượng, 1 ngày chủ động phục hồi và biết rõ chỉ số chính đang ở đâu.",
    idealFor: ["Tập luyện đều", "Sức khỏe thể chất", "Tránh chấn thương và đứt quãng"],
    goalType: "Fitness / Health",
    reviewDay: "Sunday",
    requiredPlan: "PLUS",
    accent: "emerald",
    vision12Week:
      "Trong 12 tuần tới, tôi muốn xây một nhịp tập đều, đo được tiến bộ thật và không bị đứt quãng vì kiệt sức.",
    week12Outcome:
      "Giữ nhịp tập ít nhất 3 buổi mỗi tuần liên tục và có một chỉ số sức khỏe cốt lõi được cải thiện rõ rệt.",
    lagMetricName: "Số buổi tập đã hoàn thành mỗi tuần",
    lagMetricTarget: "3",
    lagMetricUnit: "buổi/tuần",
    week4Milestone: "Nhịp 3 buổi/tuần đã thành thói quen, không còn phải cưỡng ép bản thân.",
    week8Milestone: "Chỉ số chính đã có tiến triển rõ và nhịp phục hồi đang hoạt động tốt.",
    successEvidence:
      "Bạn nhìn vào lịch là biết ngay tuần này tập ngày nào, nghỉ ngày nào và không còn tự hỏi 'hôm nay có cần tập không'.",
    tactics: [
      { name: "Buổi tập chính", target: "3", unit: "buổi/tuần", type: "core", cadence: "spread" },
      { name: "Phục hồi chủ động (giãn / đi bộ)", target: "2", unit: "lần/tuần", type: "core", cadence: "spread" },
      { name: "Ghi chỉ số và tiến triển", target: "1", unit: "lần/tuần", type: "optional", cadence: "backload" },
    ],
  },
];
